<?php
$this->id    = 'sports';
$this->title = 'Sport';
$this->wrapcenter = 'bodytext';
$this->contentleft = array('slideshow' => array(
	array('label' => 'Kanufahrt', 'image' => 'sports-kanumonster.jpg'),
	array('label' => 'Kletterpark', 'image' => 'sports-climbing.jpg'),
	array('label' => 'Kletterpark', 'image' => 'sports-climbingpark.jpg'),
));
?>
<h3>Klettern</h3>
<p>Einmal wie Tarzan von Baum zu Baum schwingen? Das ist im Syratu-Akrobatik-Kletterpark in Ornans möglich. Der direkt an der Loue gelegene Park lädt auch schon die Kleinen (ab 1,30m) ein, in Bäumen zu klettern und sich abzuseilen.</p>
<p>Wer lieber an Felsen klettert kann über Syratu auch geführte Klettertouren buchen.</p>
<h3>Kanu-/Kajaktouren</h3>
<p>In den wärmeren Monaten, wenn genügend Wasser in den Flüssen fließt, bieten (geführte) Kanu- und Kajakwanderungen auf der Loue und der Lison eine schöne Abwechslung. Die Ausrüstung und weitere Informationen gibt es bei Syratu in Ornans.</p>
<h3>Radfahren</h3>
<p>Unzählige, wenig befahrene Straßen laden zum Radfahren durch die grünen Täler, Wälder und Hochebenen des Département Doubs ein. Es gibt mehrere ausgeschilderte Rundwege verschiedener Schwierigkeitsgrade. Fahrräder, Mountainbikes und Streckenkarten kann man von Mai bis Oktober in der »Auberge« in Amondans ausleihen und wahlweise dazu noch eine geführte Tour buchen.</p>
