<?php
	$this->id = 'home';
	$this->title = null;
	$this->contentgoes = 'right';
	$this->contentcenter = array('label' => 'Front');
	$this->wrapright = 'bodytext';
?>
<p>Auf diesen Seiten stellt der Verein »Rencontres e.V.« sich und seine Ferienkolonie Val Sainte Marie vor.</p>
<p>Die ehemalige Klosterherberge liegt in Mitten schöner Landschaften der Franche-Comté unweit der Universitätsstadt Besançon.</p>
<p>Ideal geeignet ist das große Haus für Familien- und Sportfreizeiten, Klassen- und Studienfahrten und für begeisterte Frankreichurlauber, die sich gerne abseits der großen Städte in der Natur erholen möchten.</p>
