<?php
$this->id    = 'ornans';
$this->title = 'Ornans';
?>
<p>Das Städtchen Ornans liegt etwa 15km nordöstlich von Val Sainte Marie im Tal der Loue. Mit seinen direkt am Fluss gebauten Häusern ist es wohl eines der schönsten kleinen Jurastädtchen. Bekannt ist Ornans vor allem durch die Darstellung in zahlreichen Gemälden des Malers Gustave Courbet, der dort geboren und auch begraben wurde. In seinem Geburtshaus befindet sich heute das »Musée Courbet«.</p>
