<?php
$this->id    = 'vicinity';
$this->title = 'In der Nähe';
$this->wrapcenter = 'bodytext';
$this->contentleft = array('slideshow' => array(
	array('label' => 'Schloss Cleron', 'image' => 'vicinity-cleron-castle.jpg'),
	array('label' => 'Source du Lison', 'image' => 'vicinity-source-lison.jpg'),
	array('label' => 'Käserei', 'image' => 'vicinity-comte.jpg'),
	array('label' => 'Source de la Loue', 'image' => 'vicinity-source-loue.jpg'),
	array('label' => 'Dorffest Amancey', 'image' => 'vicinity-amancey.jpg'),
));
?>
<p>Die Franche-Comté ist eine der waldreichsten Regionen Frankreichs und daher ideal zum Wandern.</p>
<h3>La source de la Loue / Source du Lison</h3>
<p>Etwas außerhalb der Gemeinde Ouhans in einem Waldgebiet entspringt die Loue in einer Karstquelle. Der Lison entspringt in der Nähe von Nans-sous-Sainte-Anne ebenfalls aus einer Karstquelle. Als Karstquelle bezeichnet man einen erneut als Quelle austretenden unterirdischen Lauf eines Flusses.</p>
<p>Besonders beeindruckend sind die Quellen in den Frühjahrs- und Herbstmonaten, wenn sie außerordentlich reich an Wasser sind. Die Gebiete rund um die Quellen eignen sich hervorragend für kleine Wandertouren.</p>
<h3>Le hameau du fromage</h3>
<p>Die käsebegeisterten Besucher kommen in der Hameau du Fromage in Cleron voll auf ihre Kosten. In der Käserei mit angehängtem Museum gibt es allerlei spannende Dinge rund um die Produktion und die Geschichte der regionalen Käsesorten »Comté«, »Edel« und »Morbier« zu entdecken.</p>
<h3>Grotten und Tropfsteinhöhlen</h3>
<p>In der näheren Umgebung von Val Sainte Marie gibt es dank des kalkhaltigen Untergrunds viele Tropfsteinhöhlen und Grotten, die hauptsächlich von Anfang April bis Ende Oktober besichtigt werden können.</p>
<p>Die »Grottes d'Osselle« sind eine Höhlenformation aus rund 15 Sälen in der Nähe von Osselle. In den rund 25 km von Val Sainte Marie entfernten Höhlen gibt es durch Minerale außergewöhlich gefärbte Felsformationen zu entdecken.</p>
<p>Die Tropfsteinhöhle »Le Gouffre de Poudrey« kann man im 30 km entfernten Étalans besichtigen. Der 70m hohe unterirdische Saal wird mit seinen beleuchteten Stalagmiten und Formationen zum surreales Spektakel.</p>
<p>Die »Grotte des Planches« und die »Grottes des Moidons« befinden sich in der Nähe von Arbois etwa 30 km südwestlich von Val Sainte Marie.</p>
<p>Faszinierend ist auch die »Grotte de la Glacière« in der für gewöhnlich auch im Sommer Eis liegt. In der Nähe gibt es auch ein Mineralienmuseum zu besichtigen. Die Höhle befindet sich rund 40 km nordöstlich von Val Sainte Marie in der Nähe der Gemeinde Chaux-lès-Passavant.</p>
