<?php echo $this->doctype(); ?>
<?php
	// Language code.
	$lang = $this->Zend_Locale->getLanguage();
	// Home link plus escaped version.
	$home = $this->url(array(), 'static', true);
	$e_home = $this->escape($home);
	// Languages for language switcher.
	$langs = array(
		'de' => 'auf Deutsch',
		'fr' => 'en français',
	);
	$langlinks = array();
	foreach ($langs as $k => $v) {
		$langlinks[] = array(
			'text' => $v,
			'href' => $this->url(array('@locale' => $k, 'LOCALE' => $k)),
		);
	}
	// Social media links for social media bar.
	$social = array(
		array('text' => 'Twitter', 'href' => 'https://twitter.com/ValSainteMarie'),
		array('text' => 'Facebook', 'href' => 'https://www.facebook.com/group.php?gid=120928374601886&v=wall'),
		array('text' => 'Flickr', 'href' => 'http://www.flickr.com/photos/valstemarie/'),
	);
	// Bottom links.
	$bottomitems = array('house', 'rencontres', 'route-surroundings', 'booking', 'contact');
	$bottomlinks = array();
	foreach ($bottomitems as $v) {
		$bottomlinks[] = array(
			'text' => __("bottom-$v"),
			'href' => $this->url(array('lv1' => $v), 'static', true),
		);
	}
	// Which content divs exist.
	$contentareas = array('center', 'left', 'right');
	// In which order to output the content divs.
	$contentoutputorder = array('left', 'right', 'center');
	// Initialize the actual content array.
	$content = array();
	// Initialize content wrapper array.
	$contentwrap = array();
	// Check if there is content placed in $this->content<area>, e.g.
	// $this->contentleft. If set, add to $content.
	foreach ($contentareas as $v) {
		if (isset ($this->{"content$v"})) {
			$content[$v] = $this->{"content$v"};
		}
		if (isset ($this->{"wrap$v"})) {
			$contentwrap[$v] = $this->{"wrap$v"};
		}
	}
	// If $this->contentgoes is not set, select the first available position.
	if (!isset($this->contentgoes) || !in_array($this->contentgoes, $contentareas)) {
		// If no slot is available, the view’s content will go nowhere.
		$this->contentgoes = null;
		foreach ($contentareas as $v) {
			if (!isset($content[$v])) {
				$this->contentgoes = $v;
				break;
			}
		}
	}
	// Place the view’s main content into $this->contentgoes.
	if ($this->contentgoes !== null) {
		$content[$this->contentgoes] = $this->layout()->content;
	}
	// If any of the contents is an array, convert to an image.
	foreach ($content as $k => $v) {
		if (is_array($v)) {
			if (!isset($v['image'])) {
				$v['image'] = "{$this->id}.jpg";
			}
			if (!isset($v['label'])) {
				$v['label'] = __("{$this->id}-label");
			}
			$content[$k] = $this->partial('image.phtml', $v);
		}
	}
?>
<html lang="<?php echo $lang; ?>" class="lang-<?php echo $lang; ?> no-js">

<head>
	<?php echo $this->headMeta()->setCharset('UTF-8'); ?>
	<title><?php if (isset($this->title)) {
		echo $this->escape($this->title) . ' « ';
	} ?>Val Sainte Marie</title>
	<link rel="stylesheet" type="text/css" href="/css/2011/style.css" />
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
	<link rel="icon" href="/favicon.ico" type="image/x-icon" />
	<script src="/js/modernizr.custom.75444.js" type="text/javascript"></script>
	<script src="/js/jquery-1.6.4.min.js" type="text/javascript"></script>
	<script src="/js/jquery.cookie-1.0.0.js" type="text/javascript"></script>
	<script src="/js/valsaintemarie.js" type="text/javascript"></script>
</head>

<body<?php if (isset($this->id)) {
	echo ' id="page-' . $this->id . '"';
} ?><?php if (isset($this->bodyclass)) {
	echo ' class="' . (is_array($this->bodyclass) ? implode(' ', $this->bodyclass) : $this->bodyclass) . '"';
} ?>><div id="wrapper">
<!-- TODO: Use HTML5 semantic tags where possible. -->

<div id="top">
	<h1><a href="<?php echo $e_home; ?>">Val Sainte Marie</a></h1>
	<h2><a href="<?php echo $e_home; ?>"><?php echo __('subtitle'); ?></a></h2>
	<div id="langswitch"><?php
		echo $this->partialLoop('pipelist.phtml', $langlinks);
	?></div>
</div>

<div id="middle">
	<div id="social"><?php
		echo $this->partialLoop('pipelist.phtml', $social);
	?></div>
	<div id="main">
		<?php foreach ($contentoutputorder as $contentarea) {
			if (isset($content[$contentarea])) {
				?><div id="<?php echo $contentarea; ?>">
					<?php printf(isset($contentwrap[$contentarea])
					             ? "<div class=\"{$contentwrap[$contentarea]}\">%s</div>"
					             : '%s'
					             , $content[$contentarea]); ?>
				</div><?php
			}
		} ?>
	</div>
</div>

<div id="bottom">
	<?php echo $this->partialLoop('pipelist.phtml', $bottomlinks); ?>
</div>

</div></body>

</html>
