<?php echo $this->doctype(); ?>
<?php
	// Language code.
	$lang = $this->Zend_Locale->getLanguage();
	// Home link plus escaped version.
	$home = $this->url(array(), 'static', true);
	$e_home = $this->escape($home);
	// Languages for language switcher.
	$langs = array(
		'de' => 'auf Deutsch',
		'fr' => 'en français',
	);
	$langlinks = array();
	foreach ($langs as $k => $v) {
		$langlinks[] = array(
			'text' => $v,
			'href' => $this->url(array('@locale' => $k, 'LOCALE' => $k)),
		);
	}
	// Social media links for social media bar.
	$social = array(
		array('text' => 'Twitter', 'href' => ''),
		array('text' => 'Facebook', 'href' => ''),
		array('text' => 'Flickr', 'href' => ''),
	);
	// Bottom links.
	$bottomitems = array('house', 'rencontres', 'route-surroundings', 'booking', 'contact');
	$bottomlinks = array();
	foreach ($bottomitems as $v) {
		$bottomlinks[] = array(
			'text' => __("bottom-$v"),
			'href' => $this->url(array('lv1' => $v), 'static', true),
		);
	}
	// Which content divs to create and what to put inside them.
	$contentareas = array('center', 'left', 'right');
	if (!isset($this->contentgoes) || !in_array($this->contentgoes, $contentareas)) {
		$this->contentgoes = $contentareas[0];
	}
	$content = array(
		$this->contentgoes => $this->layout()->content,
	);
?>
<html lang="<?php echo $lang; ?>" class="lang-<?php echo $lang; ?> no-js">

<head>
	<?php echo $this->headMeta()->setCharset('UTF-8'); ?>
	<title><?php if (isset($this->title)) {
		echo $this->escape($this->title) . ' « ';
	} ?>Val Sainte Marie</title>
	<!-- TODO: Use server-side LESS. -->
	<link rel="stylesheet/less" type="text/css" href="/css/2011/style.less" />
	<script src="/js/less-1.1.3.min.js" type="text/javascript"></script>
	<script src="/js/modernizr.custom.75444.js" type="text/javascript"></script>
	<script src="/js/jquery-1.6.4.min.js" type="text/javascript"></script>
</head>

<body<?php if (isset($this->id)) {
	echo ' id="page-' . $this->id . '"';
}?>><div id="wrapper">
<!-- TODO: Use HTML5 semantic tags where possible. -->

<div id="top">
	<h1><a href="<?php echo $e_home; ?>">Val Sainte Marie</a></h1>
	<h2><a href="<?php echo $e_home; ?>"><?php echo __('subtitle'); ?></a></h2>
	<div id="langswitch"><?php
		echo $this->partialLoop('pipelist.phtml', $langlinks);
	?></div>
</div>

<div id="middle">
	<div id="social"><?php
		echo $this->partialLoop('pipelist.phtml', $social);
	?></div>
	<div id="main">
		<?php foreach ($contentareas as $contentarea) {
			if (isset($content[$contentarea])) {
				?><div id="<?php echo $contentarea; ?>"><?php echo $content[$contentarea]; ?></div><?php
			}
		} ?>
	</div>
</div>

<div id="bottom">
	<?php echo $this->partialLoop('pipelist.phtml', $bottomlinks); ?>
</div>

</div></body>

</html>
