<?php
$this->id    = 'area';
$this->title = 'Gelände';
?>
<p>Zum Haus gehören zwei große Spielwiesen, eine Feuerstelle für Lagerfeuer und eine Terrasse mit Blick auf den benachbarten Bauernhof. Auf der Spielwiese vor dem Haus befindet sich ein Volleyballnetz, die hintere Spielwiese kann hervorragend zum Fussballspielen genutzt werden. In der Eingangshalle steht eine Tischtennisplatte zur Nutzung bereit. Schläger und Bälle müssen allerdings mitgebracht oder vor Ort gekauft werden.</p>
<p>Außerdem gibt es hinter dem Haus einen Bach, der über wenige Meter steilen Waldweg erreichbar ist. Der Bach eignet sich für Wasserwanderungen und im Sommer kann sogar in einigen tieferen Bereichen schwimmen.</p>
