<?php
$this->id    = 'dining-room';
$this->title = 'Speisesaal';
?>
<p>Der Speisesaal misst 60m² und ist mit Tischen und Stühlen für 50 Personen ausgestattet. Der Saal kann in den kälteren Monaten mit zwei großen Gasöfen beheizt werden. Außerdem befindet sich im Saal ein Durchreich-Schrank zur Spülküche, in dem Gläser, Teller und das Besteck aufbewahrt werden und ein großer Schrank, in dem Schüsseln und Tablettes stehen.</p>
<p>Im angeschlossenen Telefonzimmer befinden sich neben dem Telefon noch zusätzliche Stühle und ein Schrank mit einigen Gesellschaftsspielen.</p>
