<?php
$this->id    = 'history';
$this->title = 'Geschichte';
$this->bodytextin = 'center';
$this->contentleft = array('label' => 'alte Broschüre', 'image' => 'history-brochure.jpg');
?>
<h3>Kurz die Geschichte eines großen Hauses</h3>
<p>Das Gebäude der heutigen <em>Colonie de Vacances Val Ste. Marie</em> ist die alte Beherbergungsstätte des Klosters der Trappisten, eines katholischen Ordens, der 1663 in der Abtei La Trappe/Normandie gegründet wurde. Auch heute noch reden die Bewohner der Region von der Colonie der Trappisten.</p>
<h3>Einstmals</h3>
<p>Am 11. November 1834 kamen 34 Trappisten aus der Schweiz ins Tal, das nur wenige Kilometer von Besançon entfernt liegt. Sie ließen sich behelfsmäßig in dem benachbarten Bauernhof nieder und begannen mit dem Aufbau der Beherbergungsstätte. Vermutlich aus Geldmangel konnten sie die Errichtung der geplanten Kirche nicht vollenden. In besonders trockenen Zeiten kann man noch die Fundamente im angrenzenden Feld sehen. Die Trappisten haben das Tal 1870 verlassen.</p>
<h3>Gestern</h3></h3>
<p>Im Jahre 1920 ging das Gebäude in den Besitz von Madame Pommery (Champagner-Lady) über und wurde dem Kinderchor der Kathedrale von Reims für Ferienaufenthalte zur Verfügung gestellt. Die Kinder des Chores nutzten das Haus bis zum Beginn des Zweiten Weltkrieges. Während des Krieges (1939–1945) wurde das Haus zunächst zu einem Rot-Kreuz-Lazarett umfunktioniert.</p>
<h3>Heute</h3>
<p>Das begann im Jahre 1949. Madame Pommery war inzwischen verstorben und der Erbe verkaufte das Gebäude an die Kirchengemeinde <em>„Notre-Dame-des-Anges“</em> in Belfort. Diese beschloss, das Gebäude und ein kleines Stück angrenzenden Geländes in eine Ferienkolonie umzuwandeln. Der Rest des Geländes ging in den Besitz des nächstgelegenen Dorfes Malans über. In den nächsten 10 Jahren verbrachten bereits mehr als 1400 Kinder ihre Ferien in <em>Val Sainte Marie</em>.</p>
<h3>Inzwischen</h3>
<p>Inzwischen ist aus dem „Heute“ bereits ein neues „Gestern“ geworden. Seit Anfang der 80er hatten sich einige deutsche Jugendliche und Erwachsene mit dem Gebäude, der Umgebung, der einheimischen Bevölkerung und dem Vorstand der Kirchengemeinde Notre-Dame-des Anges angefreundet. Die hohen finanziellen Belastungen und die anstehenden umfangreichen Renovierungsarbeiten zwangen die Kirchengemeinde zum Verkauf der Colonie. Da die Erhaltung des Gebäudes als preisgünstige Unterkunftsmöglichkeit für Kinder-, Jugend- und Erwachsenengruppen ein wichtiges Anliegen des inzwischen gegründeten Viernheimer Vereins <em>Rencontres</em> war, entschied sich die Kirchengemeinde beim Verkauf für „les Allemands“. Seit Juni 1988 ist der Verein Rencontres nun Besitzer dieser Ferienkolonie im Tal der heiligen Maria (Val Ste. Marie). Auch in Zukunft steht das Haus Kinder-, Jugend- und Erwachsenengruppen aus aller Welt offen.</p>
