<?php
$this->id    = 'kitchen';
$this->title = 'Küche';
$this->wrapcenter = 'bodytext';
$this->contentleft = array('slideshow' => array(
	array('label' => 'Küche', 'image' => 'kitchen-inside.jpg'),
	array('label' => 'Küche', 'image' => 'kitchen-outside.jpg'),
));
?>
<p>Die Küche ist in eine Koch- und eine Spülküche aufgeteilt. Die Kochküche ist gut ausgerüstet mit zwei Gasherden; einem zweiflammigen Herd für große Töpfe und einem vierflammigen Herd für normalgroße Töpfe. Desweiteren gibt es einen großen Kombidämpfer, zwei elektrische Bräter, Warmhalteschubladen und eine Friteuse, die nach Benutzung sauber zu machen ist. In der Kochküche befinden sich 2 große und ein kleines Waschbecken. Zusätzlich gibt es eine Wasserstelle direkt über dem zweiflammigen Herd, um große Töpfe direkt mit Wasser befüllen zu können. Kochgeschirr ist zahlreich vorhanden.</p>
<p>In der Spülküche befinden sich zwei große Spülbecken, eine Haushaltsspüle und eine Gastrospülmaschine, sowie zwei große Kühlschränke. Auf dem großen Ablageregal gefindet sich ein Baguetteschneidemesser, eine Mikrowelle und eine Gastrokaffeemaschine für rund 60 Tassen. Die Gefriertruhe befindet sich im an den Speisesaal angeschlossenen Telefonzimmer.</p>
