<?php
$this->id    = 'rooms';
$this->title = 'Zimmer';
?>
<p>Zur Zeit hat das Haus 59-75<span class="todo">?</span> Betten, die in 2- bis 6-Bett-Zimmern aufgeteilt sind. In jedem Zimmer befindet sich eine Waschecke mit Warm- und Kaltwasser, Spiegel, Ablage und Handtuchhalter. Einige Zimmer sind mit Zentralheizung, andere mit Elektrolüftern beheizbar. Ein Betreuerzimmer ist zusätzlich mit einer Toilette ausgestattet.</p>
<p>Für die Betten muss ein Bettlaken und Bettwäsche, wahlweise ein Bettlaken und ein Schlafsack mitgebracht werden.</p>
