<?php
$this->id    = 'sanitary';
$this->title = 'Sanitär';
?>
<p>Die 2009<span class="todo">?</span> frisch renovierten Sanitäranalagen befinden sich auf dem Gang in Erd- und Obergeschoss. Auf beiden Geschossen befinden sich jeweils 3 Toiletten. Im Untergeschoss befindet sich eine große Duschanlage in der gemeinschaftlich geduscht werden kann. Im Obergeschoss gibt es neben drei komfortable Einzelduschen zusätzlich ein abschließbares Duschzimmer mit Toilette.</p>
